export const CATEGORY_DATA = [
    { name: "식사", icon: "/icons/profile/meal.png", color: "#F9877A", title: "푸드 파이터" },
    { name: "카페", icon: "/icons/profile/cafe.png", color: "#F9D77A",title: "카페인 중독자" },
    { name: "음악", icon: "/icons/profile/music.png", color: "#E47AF9",title: "내 삶은 플레이리스트" },
    { name: "영화", icon: "/icons/profile/movie.png", color: "#7A8BF9",title: "팝콘 러버" },
    { name: "독서", icon: "/icons/profile/reading.png", color: "#7AB1F9",title: "책벌레" },
    { name: "운동", icon: "/icons/profile/exercise.png", color: "#C8F97A",title: "지치지 않는 자" },
    { name: "음주", icon: "/icons/profile/drinking.png", color: "#F9F97A",title: "간 괜찮으세요?" },
    { name: "학습", icon: "/icons/profile/learning.png", color: "#F9AB7A",title: "지식 탐험가" },
    { name: "쇼핑", icon: "/icons/profile/shopping.png", color: "#7AF97A",title: "쇼핑 중독자" },
    { name: "병원", icon: "/icons/profile/hospital.png", color: "#7AECF9",title: "병원 VIP" },
    { name: "게임", icon: "/icons/profile/game.png", color: "#A07AF9",title: "만렙 유저" },
    { name: "여행", icon: "/icons/profile/travel.png", color: "#F97AAD",title: "빠니보틀의 후예" },
    { name: "신한", icon: "/icons/category/shinhanicon.png", color: "#357ABD", title: "교육을 들은 자"},
  ];