import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export default function SearchPanel({ searchQuery, setSearchQuery, searchResults, handleSearch, handleResultClick, inputRef, hasNextPage, currentPage, onOpenModal, }) {
    return (_jsxs("div", { className: 'flex flex-col h-full bg-white', children: [_jsxs("div", { className: 'flex p-2', children: [_jsx("input", { ref: inputRef, type: 'text', placeholder: '\uAC80\uC0C9\uC5B4\uB97C \uC785\uB825\uD558\uC138\uC694', className: 'flex-1 px-3 py-3 border border-gray-300 rounded-l-lg text-base outline-none', value: searchQuery, onChange: (e) => setSearchQuery(e.target.value), onKeyDown: (e) => {
                            if (e.key === "Enter") {
                                handleSearch(1);
                                e.currentTarget.blur();
                            }
                        }, "aria-label": '\uC7A5\uC18C \uAC80\uC0C9' }), _jsx("button", { type: 'button', onClick: () => handleSearch(1), className: 'px-3 border border-blue-500 bg-blue-500 text-white rounded-r-lg flex items-center justify-center cursor-pointer', children: "\uD83D\uDD0D" })] }), _jsxs("div", { className: 'flex-1 p-2 overflow-y-auto', children: [searchResults.map((item, idx) => (_jsxs("div", { className: 'flex justify-between items-center py-2 border-b border-gray-200', children: [_jsxs("div", { className: 'text-left', children: [_jsx("div", { className: 'font-medium', children: item.name }), _jsx("div", { className: 'text-sm text-gray-500', children: item.address })] }), _jsx("button", { type: 'button', onClick: () => onOpenModal(item), className: 'ml-2 px-3 py-1 rounded-lg bg-green-500 text-white text-sm', children: "\uB9C1\uCEE4 \uCD94\uAC00" })] }, idx))), hasNextPage && (_jsx("button", { type: 'button', onClick: () => handleSearch(currentPage + 1), className: 'w-full py-2 mt-2 rounded-lg bg-blue-500 text-white cursor-pointer', children: "\uACC4\uC18D \uAC80\uC0C9\uD558\uAE30" })), searchResults.length === 0 && searchQuery && (_jsx("div", { className: 'text-gray-400 mt-2', children: "\uAC80\uC0C9 \uACB0\uACFC\uAC00 \uC5C6\uC2B5\uB2C8\uB2E4." }))] })] }));
}
